// Code generated by protoc-gen-go.
// source: guid.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	guid.proto

It has these top-level messages:
	EmptyRequest
	IdWorkerReply
	IdReply
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyRequest struct {
}

func (m *EmptyRequest) Reset()                    { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string            { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()               {}
func (*EmptyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type IdWorkerReply struct {
	WorkerId     uint64 `protobuf:"varint,1,opt,name=workerId" json:"workerId,omitempty"`
	DatacenterId uint64 `protobuf:"varint,2,opt,name=datacenterId" json:"datacenterId,omitempty"`
	Timestamp    int64  `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *IdWorkerReply) Reset()                    { *m = IdWorkerReply{} }
func (m *IdWorkerReply) String() string            { return proto.CompactTextString(m) }
func (*IdWorkerReply) ProtoMessage()               {}
func (*IdWorkerReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IdWorkerReply) GetWorkerId() uint64 {
	if m != nil {
		return m.WorkerId
	}
	return 0
}

func (m *IdWorkerReply) GetDatacenterId() uint64 {
	if m != nil {
		return m.DatacenterId
	}
	return 0
}

func (m *IdWorkerReply) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type IdReply struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *IdReply) Reset()                    { *m = IdReply{} }
func (m *IdReply) String() string            { return proto.CompactTextString(m) }
func (*IdReply) ProtoMessage()               {}
func (*IdReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IdReply) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "main.EmptyRequest")
	proto.RegisterType((*IdWorkerReply)(nil), "main.IdWorkerReply")
	proto.RegisterType((*IdReply)(nil), "main.IdReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Worker service

type WorkerClient interface {
	GetIdWorker(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*IdWorkerReply, error)
	GetId(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*IdReply, error)
}

type workerClient struct {
	cc *grpc.ClientConn
}

func NewWorkerClient(cc *grpc.ClientConn) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) GetIdWorker(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*IdWorkerReply, error) {
	out := new(IdWorkerReply)
	err := grpc.Invoke(ctx, "/main.Worker/GetIdWorker", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) GetId(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*IdReply, error) {
	out := new(IdReply)
	err := grpc.Invoke(ctx, "/main.Worker/GetId", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Worker service

type WorkerServer interface {
	GetIdWorker(context.Context, *EmptyRequest) (*IdWorkerReply, error)
	GetId(context.Context, *EmptyRequest) (*IdReply, error)
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_GetIdWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).GetIdWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Worker/GetIdWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).GetIdWorker(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_GetId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).GetId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Worker/GetId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).GetId(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIdWorker",
			Handler:    _Worker_GetIdWorker_Handler,
		},
		{
			MethodName: "GetId",
			Handler:    _Worker_GetId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guid.proto",
}

func init() { proto.RegisterFile("guid.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0x5a, 0x0a, 0x3d, 0xda, 0x0e, 0xc7, 0x52, 0x22, 0x86, 0xca, 0x53, 0x91, 0x90,
	0x07, 0x58, 0x98, 0x2b, 0xa1, 0x2a, 0x5b, 0xe5, 0x85, 0xd9, 0xad, 0xad, 0xd4, 0x02, 0xc7, 0x26,
	0x3e, 0x0b, 0x95, 0x5f, 0x8f, 0xe2, 0x10, 0x20, 0x12, 0xe3, 0xbd, 0x77, 0x4f, 0xef, 0xd3, 0x03,
	0xa8, 0xa2, 0x51, 0xdc, 0x37, 0x8e, 0x1c, 0x8e, 0xad, 0x34, 0x35, 0x5b, 0xc0, 0xec, 0xd9, 0x7a,
	0x3a, 0x09, 0xfd, 0x1e, 0x75, 0x20, 0x66, 0x61, 0x5e, 0xaa, 0x17, 0xd7, 0xbc, 0xea, 0x46, 0x68,
	0xff, 0x76, 0xc2, 0x02, 0x2e, 0x3f, 0xd2, 0x59, 0xaa, 0x65, 0xb6, 0xca, 0xd6, 0x63, 0xf1, 0x73,
	0x23, 0x83, 0x99, 0x92, 0x24, 0x0f, 0xba, 0xa6, 0xe4, 0xe7, 0xc9, 0x1f, 0x68, 0x78, 0x0b, 0x53,
	0x32, 0x56, 0x07, 0x92, 0xd6, 0x2f, 0x47, 0xab, 0x6c, 0x3d, 0x12, 0xbf, 0x02, 0xbb, 0x81, 0x8b,
	0x52, 0x75, 0x45, 0x0b, 0xc8, 0x4d, 0x5f, 0x91, 0x1b, 0xf5, 0xe0, 0x61, 0xd2, 0x71, 0xe0, 0x13,
	0x5c, 0x6d, 0x35, 0xf5, 0x58, 0x88, 0xbc, 0x25, 0xe7, 0x7f, 0xb1, 0x8b, 0xeb, 0x4e, 0x1b, 0xa0,
	0xb3, 0x33, 0xbc, 0x87, 0xf3, 0x94, 0xfc, 0x37, 0x33, 0xef, 0x33, 0xdf, 0xdf, 0x9b, 0x3b, 0x28,
	0x0e, 0xce, 0xf2, 0xca, 0xd0, 0x31, 0xee, 0x79, 0x70, 0xc1, 0x7d, 0x1e, 0xa3, 0xac, 0x2b, 0xde,
	0xae, 0xb6, 0x99, 0x6e, 0xa3, 0x51, 0xbb, 0x76, 0xba, 0x5d, 0xb6, 0x9f, 0xa4, 0x0d, 0x1f, 0xbf,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x0a, 0xa6, 0xf9, 0x51, 0x01, 0x00, 0x00,
}
